# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'module', '0001_initial'), (b'module', '0002_auto_20160928_1701'), (b'module', '0003_auto_20161012_0016'), (b'module', '0004_activity_visible'), (b'module', '0005_sequenceitem_method'), (b'module', '0006_usermodule_max_points'), (b'module', '0007_activity_max_points'), (b'module', '0008_auto_20161012_2146'), (b'module', '0009_remove_attempt_username'), (b'module', '0010_auto_20161014_0614'), (b'module', '0011_attempt_manual')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('usage_id', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('points', models.FloatField()),
                ('max_points', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SequenceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('timestamp_created', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0)),
                ('last_position', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sequenceitem',
            name='user_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.UserModule'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='sequence_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.SequenceItem'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module'),
        ),
        migrations.AlterField(
            model_name='sequenceitem',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequenceitem',
            name='method',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='sequenceitem',
            unique_together=set([('user_module', 'position')]),
        ),
        migrations.RemoveField(
            model_name='module',
            name='max_points',
        ),
        migrations.AddField(
            model_name='activity',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to=b'module.Activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[(b'problem', b'problem'), (b'html', b'html')], default='problem', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_points',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='max_points',
            field=models.FloatField(null=True),
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='username',
        ),
        migrations.AddField(
            model_name='attempt',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
