# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0004_remove_ltisource_activity'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='launch_url',
        ),
        migrations.AddField(
            model_name='activity',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge_lti.LtiSource'),
        ),
    ]
