# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0009_auto_20170822_2101'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequenceitem',
            options={'ordering': ['position'], 'verbose_name': 'Sequence Item', 'verbose_name_plural': 'Sequence Items'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='activity',
            name='lti_consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge_lti.LtiConsumer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_context_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_launch_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='difficulty',
            field=models.CharField(choices=[(b'l', 'low'), (b'm', 'medium'), (b'h', 'high')], default=b'm', max_length=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Collection'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='lti_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge_lti.LtiUser'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='launch_url',
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('source_launch_url', 'collection')]),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set([('lti_user', 'collection')]),
        ),
    ]
