# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0006_auto_20170817_0708'),
        ('module', '0003_auto_20170817_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequenceitem',
            options={'ordering': ['position'], 'verbose_name': 'Sequence Item', 'verbose_name_plural': 'Sequence Items'},
        ),
        migrations.AlterField(
            model_name='log',
            name='attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Collection'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='lti_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge_lti.LtiUser'),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set([('lti_user', 'collection')]),
        ),
    ]
