# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20170816_1224'),
        ('module', '0004_auto_20170818_0731'),
    ]

    operations = [
    ]
