# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_sequenceitem_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodule',
            name='max_points',
            field=models.FloatField(null=True),
        ),
    ]
