# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_usermodule_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_points',
            field=models.FloatField(null=True),
        ),
    ]
