# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_auto_20170823_1538'),
        ('module', '0007_auto_20170823_1559'),
    ]

    operations = [
    ]
