# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_activity_max_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodule',
            name='max_points',
        ),
        migrations.AddField(
            model_name='module',
            name='max_points',
            field=models.FloatField(null=True),
        ),
    ]
