# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_auto_20161012_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='username',
        ),
    ]
