FROM python:3.6
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y vim

RUN mkdir /bridge_adaptivity
WORKDIR /bridge_adaptivity
ADD . /bridge_adaptivity/

# Install requirements:
RUN pip install -U pip
RUN pip install -Ur requirements.txt

# Make static media dir:
RUN mkdir -p /www/static

EXPOSE 8000
