version: '3.4'
services:
  bridge:
    image: bridge_adaptivity:local
    ports:
      - "8008:8000"
    stdin_open: true
    tty: true

  # Celery worker
  worker:
    image: bridge_adaptivity:local
