# Dockerfile for bridge-adaptivity that installs prod requirements before copying other files to image
# to take advantage of layer caching for potentially faster rebuilds/pushes

FROM python:3.6
ENV PYTHONUNBUFFERED 1

WORKDIR /bridge_adaptivity

# Install requirements:
COPY requirements.txt .
COPY requirements_base.txt .
RUN pip install -r requirements.txt

ADD . .

EXPOSE 8000
