# This is the docker-compose configuration file for running stage. This file uses the docker-compose.yml as base configuration and changes a part of configuration.
# You can run the next command and see the resulting configuration:
# 'make config-stage'
# You can see this command in bridge_adaptivity/Makefile.
version: '3.4'
services:
  bridge:
    image: bridge_adaptivity:local
    ports:
      - "8008:8000"
    stdin_open: true
    tty: true

  # Celery worker
  worker:
    image: bridge_adaptivity:local
