# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0005_remove_ltiparameters_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiparameters',
            name='roles',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
