# Serves for configuration of CodeClimate (automated code review for test coverage, complexity, duplication, etc.)
engines:
  radon:
    enabled: true
    config:
      python_version: 2
      threshold: "C"
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - NOTE
        - TODO
        - WARNING
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
        - python:
            python_version: 2
  eslint:
    enabled: true
  markdownlint:
    enabled: true

ratings:
   paths:
   - "**.js"
   - "**.py"
   - "**.md"

