# Serves for configuration of CodeClimate (automated code review for test coverage, complexity, duplication, etc.)
engines:
  radon:
    enabled: true
    config:
      python_version: 3
      threshold: "C"
  fixme:
    enabled: true
    config:
      strings:
        - BUG
        - FIXME
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
        - python:
            python_version: 3
  eslint:
    enabled: true
  markdownlint:
    enabled: true

checks:
  argument-count:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 2000
  identical-code:
    config:
      threshold: 35
  return-statements:
    config:
      threshold: 6
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 15


ratings:
   paths:
   - "**.js"
   - "**.py"
   - "**.md"

exclude_paths:
- "**/migrations/"
- "bridge_adaptivity/config/test_runner.py"
- "**/tests/"
