# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170823_1559'),
        ('api', '0002_auto_20170823_1527'),
    ]

    operations = [
    ]
