# Generated by Django 2.1.7 on 2019-03-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='modulegroup',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
