# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='correctness_matters',
            field=models.BooleanField(default=True),
        ),
    ]
