# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0002_collection_correctness_matters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('atime', models.DateTimeField(auto_now_add=True)),
                ('collections', models.ManyToManyField(to='module.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'mock', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Engine'),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
