# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0010_outcomeservice'),
        ('module', '0002_auto_20170828_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='lis_result_sourcedid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='outcome_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge_lti.OutcomeService'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='total_points',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set([('lti_user', 'collection'), ('lis_result_sourcedid', 'outcome_service')]),
        ),
    ]
