# Generated by Django 2.1.7 on 2019-03-26 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0002_auto_20190321_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_permission', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.ModuleGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='modulegroup',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='module_groups', through='module.ContributorPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
