# Generated by Django 2.1.7 on 2019-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20190326_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionorder',
            name='congratulation_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine',
            field=models.CharField(choices=[('engine_vpal', 'vpal'), ('engine_mock', 'mock')], default='engine_mock', max_length=100),
        ),
    ]
