# Generated by Django 2.0.5 on 2018-08-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20180717_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='source_context_id',
        ),
    ]
