# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20170905_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='trials',
            field=models.PositiveIntegerField(blank=True, default=0, help_text=b"Grade policy: 'N'"),
        ),
        migrations.AlterField(
            model_name='collection',
            name='threshold',
            field=models.FloatField(blank=True, help_text=b"Grade policy: 'Q'", null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='total_points',
            field=models.FloatField(blank=True, default=0, help_text=b"Grade policy: 'P'"),
        ),
    ]
