# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20170905_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceitem',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
