# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20171215_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='engine',
            unique_together=set([('host', 'token')]),
        ),
    ]
