# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 14:47
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion

from module.models import CollectionGroup

def migrate_data_forward(apps, schema_editor):
    for instance in CollectionGroup.objects.all():
        print "Generating slug for %s" % instance
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20171226_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=b'name', unique_with=[b'owner']),
        ),
        migrations.AddField(
            model_name='sequence',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Engine'),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),

    ]
