# Generated by Django 2.0.5 on 2018-09-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_remove_activity_source_context_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Collection')),
            ],
            options={
                'ordering': ('group', 'order'),
            },
        ),
        migrations.RemoveField(
            model_name='collectiongroup',
            name='collections',
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_groups', through='module.CollectionOrder',
                                         to='module.Collection'),
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.CollectionGroup'),
        ),
    ]
