# Generated by Django 2.0.5 on 2018-06-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0003_auto_20180604_1350'),
        ('module', '0004_auto_20180604_1350'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('lti_user', 'collection', 'group', 'suffix')},
        ),
    ]
