# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20180109_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_name', models.CharField(max_length=255)),
                ('threshold', models.PositiveIntegerField(blank=True, default=0, help_text=b"Grade policy: 'Q'")),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='correctness_matters',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='threshold',
        ),
        migrations.AddField(
            model_name='engine',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequence',
            name='collection_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.CollectionGroup'),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='grading_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.GradingPolicy'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='grading_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.GradingPolicy'),
        ),
    ]
