# Generated by Django 2.0.5 on 2018-06-21 08:14

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20180605_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=slugger.fields.AutoSlugField(default=1, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
