# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20180111_1838'),
        ('module', '0005_auto_20180119_1446'),
    ]

    operations = [
    ]
