# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 13:58
from __future__ import unicode_literals

from django.db import migrations


def swap_field_type(apps, schema_editor):
    Collection = apps.get_model('module', 'Collection')
    for collection in Collection.objects.all():
        collection.threshold = 0
        collection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20170907_1353'),
    ]

    operations = [
	migrations.RunPython(swap_field_type),
    ]
