# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20180104_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroup',
            name='grading_policy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.GradingPolicy'),
        ),
    ]
