# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_merge_20180119_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
