# Generated by Django 2.0.5 on 2018-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_auto_20181001_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='ui_option',
            field=models.CharField(blank=True, choices=[('AT', 'Questions answered/total'), ('EP', 'Earned points')], max_length=2),
        ),
    ]
