# Generated by Django 2.0.5 on 2019-01-04 21:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    replaces = [('module', '0007_collectiongroup_ui_option'), ('module', '0008_auto_20181126_1103'), ('module', '0009_auto_20181126_1328')]

    dependencies = [
        ('module', '0006_auto_20181001_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='ui_option',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AT', 'Questions viewed/total'), ('EP', 'Earned grade'), ('RW', 'Answers right/wrong')], help_text='Add an optional UI block to the student view', max_length=8),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='ui_next',
            field=models.BooleanField(default=False, help_text='Add an optional NEXT button under the embedded unit.'),
        ),
    ]
