# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_auto_20170907_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, default=0, help_text=b"Grade policy: 'Q'"),
        ),
    ]
