# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 13:01
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_merge_20180119_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=b'name', unique_with=(b'atime',)),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, default=1, help_text=b"Grade policy: 'Q'"),
        ),
    ]
