# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 15:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_merge_20180119_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=b'name', unique_with=(b'atime',)),
        ),
    ]
