# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_collection_updated_at'),
        ('module', '0007_auto_20180124_1532'),
    ]

    operations = [
    ]
