# Generated by Django 2.0.5 on 2018-11-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_collectiongroup_ui_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='ui_next',
            field=models.BooleanField(default=False, help_text='Add an optional NEXT button under the embedded unit.'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='ui_option',
            field=models.CharField(blank=True, choices=[('AT', 'Questions viewed/total'), ('EP', 'Earned grade'), ('RW', 'Answers right/wrong')], help_text='Add an optional UI block to the student view', max_length=2),
        ),
    ]
