# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_auto_20170907_1420'),
        ('module', '0004_sequenceitem_score'),
    ]

    operations = [
    ]
