# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_auto_20180126_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='stype',
            field=models.CharField(blank=True, help_text=b'(problem, video, html, etc.)', max_length=25, null=True, verbose_name=b'Type of activity'),
        ),
        migrations.AddField(
            model_name='sequenceitem',
            name='is_problem',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine',
            field=models.CharField(choices=[(b'engine_mock', b'mock'), (b'engine_vpal', b'vpal')], default=b'engine_mock', max_length=100),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, default=0, help_text=b"Grade policy: 'Q'"),
        ),
    ]
