# Generated by Django 2.0.5 on 2018-11-26 13:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_auto_20181126_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroup',
            name='ui_option',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AT', 'Questions viewed/total'), ('EP', 'Earned grade'), ('RW', 'Answers right/wrong')], help_text='Add an optional UI block to the student view', max_length=8),
        ),
    ]
