# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_merge_20170908_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='trials',
        ),
        migrations.RemoveField(
            model_name='sequenceitem',
            name='points',
        ),
        migrations.AlterField(
            model_name='sequenceitem',
            name='score',
            field=models.FloatField(blank=True, help_text=b"Grade policy: 'p' (problem's current score).", null=True),
        ),
        migrations.AlterField(
            model_name='sequenceitem',
            name='sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='module.Sequence'),
        ),
    ]
