# Generated by Django 2.1.3 on 2019-01-15 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_auto_20181126_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionorder',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Engine'),
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='grading_policy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.GradingPolicy'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine',
            field=models.CharField(choices=[('engine_mock', 'mock'), ('engine_vpal', 'vpal')], default='engine_mock', max_length=100),
        ),
    ]
