# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_auto_20180207_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroup',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_groups', to='module.Collection'),
        ),
    ]
