# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_auto_20180207_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, help_text=b'Provide your tags separated by a comma.', max_length=255, null=True),
        ),
    ]
