# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_auto_20170914_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequenceitem',
            options={'ordering': ['sequence', 'position'], 'verbose_name': 'Sequence Item', 'verbose_name_plural': 'Sequence Items'},
        ),
        migrations.AlterField(
            model_name='sequenceitem',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
