# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 16:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_auto_20180216_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='lti_parameters',
            field=models.TextField(blank=True, default=b'', help_text='LTI parameters to sent to the engine, use comma separated string'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
