# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_auto_20180212_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroup',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
