# Generated by Django 2.1.3 on 2019-02-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_auto_20190115_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroup',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Engine'),
        ),
    ]
