# Generated by Django 2.1.3 on 2019-02-21 08:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0011_auto_20190214_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiongroup',
            name='ui_next',
        ),
        migrations.RemoveField(
            model_name='collectiongroup',
            name='ui_option',
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='ui_next',
            field=models.BooleanField(default=False, help_text='Add an optional NEXT button under the embedded unit.'),
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='ui_option',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AT', 'Questions viewed/total'), ('EP', 'Earned grade'), ('RW', 'Answers right/wrong')], help_text='Add an optional UI block to the student view', max_length=8),
        ),
    ]
