# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0011_auto_20180220_1644',),
        ('module', '0011_auto_20180220_1552',),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingpolicy',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Engine'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
