# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0011_auto_20180220_1644'),
        ('module', '0011_auto_20180220_1552'),
    ]

    operations = [
    ]
