# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('module', '0012_auto_20170914_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
