# Generated by Django 2.1.3 on 2019-02-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0012_auto_20190221_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='strict_forward',
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='strict_forward',
            field=models.BooleanField(default=True),
        ),
    ]
