# Generated by Django 2.1.3 on 2019-02-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0005_lticonsumer_available_in_groups'),
        ('module', '0013_auto_20190221_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='collection_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.CollectionOrder'),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('lti_user', 'collection', 'collection_order', 'suffix')},
        ),
    ]
