# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0013_auto_20170914_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='atype',
            field=models.CharField(choices=[(b'G', 'generic'), (b'A', 'pre-assessment'), (b'Z', 'post-assessment')], default=b'G', max_length=1, verbose_name=b'type'),
        ),
    ]
