# Generated by Django 2.1.3 on 2019-02-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0014_auto_20190221_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='group',
        ),
    ]
