# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 09:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0015_auto_20170915_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[(b'AC', b'Activity created'), (b'AU', b'Activity updated'), (b'AD', b'Activity deleted'), (b'CC', b'Collection created'), (b'CU', b'Collection updated')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='activity',
            name='atype',
            field=models.CharField(choices=[(b'G', 'generic'), (b'A', 'pre-assessment'), (b'Z', 'post-assessment')], default=b'G', help_text=b"Choose 'pre/post-assessment' activity type to pin Activity to the start or the end of the Collection.", max_length=1, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, help_text=b'Provide your tags separated by a comma.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[(b'O', b'Opened'), (b'S', b'Submitted'), (b'A', b'Admin')], max_length=32),
        ),
    ]
