# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 13:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0016_auto_20170918_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(default=b'Unknown', help_text=b'Provide your tags separated by a comma.', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(blank=True, choices=[(b'AC', b'Activity created'), (b'AU', b'Activity updated'), (b'AD', b'Activity deleted'), (b'CC', b'Collection created'), (b'CU', b'Collection updated')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
