# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


def swap_values(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    RANGES = {
        'l': 0,
        'm': 1,
        'h': 2
    }

    Activity = apps.get_model('module', 'Activity')
    for activity in Activity.objects.all():
        activity.difficulty = RANGES[activity.difficulty]
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0017_auto_20170920_1331'),
    ]

    operations = [
        migrations.RunPython(swap_values),
        migrations.AlterField(
            model_name='activity',
            name='difficulty',
            field=models.FloatField(
                default=b'0.5',
                help_text=b'Provide float number in the range 0.0 - 2.0',
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0)
                ]
            ),
        ),
    ]
