# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'bridge_lti', '0001_initial'), (b'bridge_lti', '0002_ltiparameters_timestamp'), (b'bridge_lti', '0003_auto_20160922_1654'), (b'bridge_lti', '0004_ltiparameters_max_points'), (b'bridge_lti', '0005_remove_ltiparameters_max_points'), (b'bridge_lti', '0006_ltiparameters_roles')]

    initial = True

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='')),
                ('lis_outcome_service_url', models.CharField(default='', max_length=300)),
                ('lis_result_sourcedid', models.CharField(default='', max_length=300)),
                ('oauth_consumer_key', models.CharField(default='', max_length=300)),
                ('user_id', models.CharField(default='', max_length=300)),
                ('lis_person_sourcedid', models.CharField(default='', max_length=300)),
                ('user_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='module.UserModule')),
                ('timestamp_last_launch', models.DateTimeField(auto_now=True, null=True)),
                ('roles', models.CharField(default=b'', max_length=300)),
            ],
            options={
                'verbose_name': 'LTI Parameters',
                'verbose_name_plural': 'LTI Parameters',
            },
        ),
    ]
