# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiparameters',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
