# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('bridge_lti', '0002_ltisource'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltisource',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Activity'),
        ),
    ]
