# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0005_remove_lticonsumer_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeuser',
            name='roles',
            field=models.CharField(help_text='User <a target="_blank" href="https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-22">LTI roles</a> (comma separated).', max_length=255),
        ),
        migrations.AlterField(
            model_name='ltiuser',
            name='bridge_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
