# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0005_remove_lticonsumer_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='host_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bridgeuser',
            name='roles',
            field=models.CharField(help_text='User <a target="_blank" href="https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-22">LTI roles</a> (comma separated).', max_length=255),
        ),
    ]
