# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0006_auto_20170816_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Are its sources available for Instructors?'),
        ),
    ]
