# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_url', models.URLField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lti_consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge_lti.LtiConsumer')),
            ],
            options={
                'verbose_name': 'LTI Source',
                'verbose_name_plural': 'LTI Sources',
            },
        ),
    ]
