# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_oauthclient_content_provider'),
        ('bridge_lti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='o_auth_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_clients', to='api.OAuthClient'),
        ),
    ]
