# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0002_lticonsumer_o_auth_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lticonsumer',
            options={'verbose_name': 'Content Source', 'verbose_name_plural': 'Content Sources'},
        ),
        migrations.AlterModelOptions(
            name='ltiprovider',
            options={'verbose_name': 'LMS Platform', 'verbose_name_plural': 'LMS Platforms'},
        ),
        migrations.AlterField(
            model_name='lticonsumer',
            name='o_auth_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OAuthClient'),
        ),
    ]
