# Generated by Django 2.0.5 on 2018-06-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0003_auto_20180604_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='source_type',
            field=models.CharField(choices=[('base', 'Base Source'), ('edx', 'edX Source')], default='edx', max_length=100),
        ),
    ]
