# Generated by Django 2.0.5 on 2018-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0003_auto_20180717_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticonsumer',
            name='source_type',
            field=models.CharField(choices=[('base', 'Base Source'), ('edx', 'edX Source'), ('dart', 'Dart Source')], default='edx', max_length=100),
        ),
    ]
