# Generated by Django 2.1.4 on 2019-01-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('bridge_lti', '0004_auto_20180820_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='available_in_groups',
            field=models.ManyToManyField(related_name='group_source', to='auth.Group', verbose_name='source in groups'),
        ),
    ]
