# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0006_auto_20170817_0708'),
        ('bridge_lti', '0007_lticonsumer_is_active'),
    ]

    operations = [
    ]
