# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_lti', '0008_merge_20170821_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltisource',
            name='lti_consumer',
        ),
        migrations.DeleteModel(
            name='LtiSource',
        ),
    ]
