# Generated by Django 2.1.5 on 2019-02-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('grant_type', models.CharField(blank=True, choices=[('code', 'authorization code'), ('credentials', 'client credentials')], default='credentials', help_text='OAuth grant type which is used by Client API.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'OAuth Client',
                'verbose_name_plural': 'OAuth Clients',
            },
        ),
    ]
