# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bridge_lti', '0009_auto_20170822_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('grant_type', models.CharField(blank=True, choices=[(b'code', b'authorization code'), (b'implicit', b'implicit'), (b'password', b'resource owner password-based'), (b'credentials', b'client credentials')], max_length=255, null=True)),
                ('content_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge_lti.LtiConsumer')),
            ],
            options={
                'verbose_name': 'OAuth Client',
                'verbose_name_plural': 'OAuth Clients',
            },
        ),
    ]
