# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='content_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_clients', to='bridge_lti.LtiConsumer'),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='grant_type',
            field=models.CharField(blank=True, choices=[(b'code', b'authorization code'), (b'implicit', b'implicit'), (b'password', b'resource owner password-based'), (b'credentials', b'client credentials')], default=b'credentials', help_text=b'OAuth grant type which is used by OpenEdx API.', max_length=255, null=True),
        ),
    ]
