# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthclient',
            name='content_provider',
        ),
    ]
