# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='content_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_clients', to='bridge_lti.LtiConsumer'),
        ),
    ]
