# Generated by Django 2.0.5 on 2018-07-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180604_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
