# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0004_ltiparameters_max_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiparameters',
            name='max_points',
        ),
    ]
