FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
ADD sites-enabled/bridge-stage.conf /etc/nginx/conf.d
RUN mkdir /etc/nginx/ssl
ADD ssl/* /etc/nginx/ssl/

RUN apt-get update && apt-get install -y vim
